1:
  success: 80
  destroy: 0
2:
  success: 75
  destroy: 5
3:
  success: 70
  destroy: 10
4:
  success: 60
  destroy: 15
5:
  success: 55
  destroy: 20
6:
  success: 50
  destroy: 25
7:
  success: 40
  destroy: 30
8:
  success: 35
  destroy: 35
9:
  success: 30
  destroy: 40
10:
  success: 26
  destroy: 45
11:
  success: 22
  destroy: 50
12:
  success: 18
  destroy: 55
13:
  success: 14
  destroy: 60
14:
  success: 10
  destroy: 65
15:
  success: 8
  destroy: 70
16:
  success: 6
  destroy: 75
17:
  success: 5
  destroy: 80
18:
  success: 4
  destroy: 85
19:
  success: 3
  destroy: 90
20:
  success: 0
  destroy: 100