- Items:
  - Krump_Wep_Pickaxe_Antler2
  - Krump_Wep_FishingRod_03
  - Krump_Wep_FishingRod_04
  - Krump_Wep_Knife_Butcher
  - D_Stone_Butcher
  - D_Stone_Sickle
  - D_Primitive_Plant_Hoe
  - D_Bronze_Butcher
  - D_Finewood_Sickle
  - D_Iproved_Butcher
  - D_FineWood_Plant_Hoe
  - Krump_Wep_Pickaxe_Bronze2
  - D_Iron_Butcher
  - D_Iron_Sickle
  - D_Iron_Plant_Hoe
  - Krump_Wep_Pickaxe_Iron3
  - Krump_Wep_Shovel
  Stats:
    1:
      durability_percentage: 5
      attack_speed: 10
    2:
      durability_percentage: 10
      attack_speed: 20
    3:
      durability_percentage: 15
      attack_speed: 30
    4:
      durability_percentage: 20
      attack_speed: 40
    5:
      durability_percentage: 25
      attack_speed: 50
    6:
      durability_percentage: 30
      attack_speed: 60
    7:
      durability_percentage: 35
      attack_speed: 70
    8:
      durability_percentage: 40
      attack_speed: 80
    9:
      durability_percentage: 45
      attack_speed: 90
    10:
      durability_percentage: 50
      attack_speed: 100
    11:
      durability_percentage: 55
      attack_speed: 110
    12:
      durability_percentage: 60
      attack_speed: 120
    13:
      durability_percentage: 65
      attack_speed: 130
    14:
      durability_percentage: 70
      attack_speed: 140
    15:
      durability_percentage: 75
      attack_speed: 150
    16:
      durability_percentage: 80
      attack_speed: 160
    17:
      durability_percentage: 85
      attack_speed: 170
    18:
      durability_percentage: 90
      attack_speed: 180
    19:
      durability_percentage: 95
      attack_speed: 190
    20:
      durability_percentage: 100
      attack_speed: 200
