- Items:
  - SwordCheat
  - SledgeCheat
  Colors:
    1:
      color: '#00190019'
    2:
      color: '#00320032'
    3:
      color: '#004B004B'
    4:
      color: '#00640064'
    5:
      color: '#007D007D'
    6:
      color: '#00960096'
    7:
      color: '#00AF00AF'
    8:
      color: '#00C800C8'
    9:
      color: '#00E100E1'
    10:
      color: '#00FA00FA'
